apiVersion: v1
kind: Secret
metadata:
  name: r2r-hatchet-secrets
  namespace: ai-system
type: Opaque
stringData:
  HATCHET_DATABASE_POSTGRES_POSTGRES_PASSWORD: "s54c2xh756n90in6h7b76v3dh"

  # user-app password
  HATCHET_DATABASE_POSTGRES_PASSWORD: "skrbgsfk8f4v8bw9fchf9"

  # optional - for replication
  # HATCHET_DATABASE_POSTGRES_REPLICA_PASSWORD: "CHANGE_ME_replica_password"
