apiVersion: batch/v1
kind: Job
metadata:
  name: dummy-not-used
spec:
  template:
    spec:
      volumes:
        - name: hatchet-keys
          secret:
            defaultMode: 256
            secretName: hatchet-keyset
      containers:
        - name: setup-worker-token
          volumeMounts:
            - mountPath: /etc/hatchet/keys
              name: hatchet-keys
              readOnly: true
