auth:
  existingSecret: r2r-hatchet-secrets
  secretKeys:
    adminPasswordKey: HATCHET_DATABASE_POSTGRES_POSTGRES_PASSWORD
    userPasswordKey: HATCHET_DATABASE_POSTGRES_PASSWORD
    replicationPasswordKey: HATCHET_DATABASE_POSTGRES_REPLICA_PASSWORD

#creates hatchet database
global:
  storageClass: csi-sc
  postgresql:
    auth:
      database: hatchet

primary:
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  initdb:
    scripts:
      01-create-extra-db.sql: |
        CREATE DATABASE r2r;
        GRANT ALL PRIVILEGES ON DATABASE r2r TO postgres;
