---
apiVersion: v1
kind: Secret
metadata:
  name: r2r-secret
  namespace: r2r-dev
  labels:
    app: r2r
data:
  R2R_POSTGRES_USER: cG9zdGdyZXM=
  R2R_POSTGRES_PASSWORD: cG9zdGdyZXM=
  AZURE_API_KEY: <Put Azure OpenAPI Key>