apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: r2r-configmap
  namespace: ai-system
data:
  AWS_REGION_NAME: ""
  AZURE_API_BASE: ""
  AZURE_API_VERSION: ""
  AZURE_FOUNDRY_API_ENDPOINT: ""
  CLUSTERING_SERVICE_URL: http://r2r-graph-clustering:7276
  GITHUB_REDIRECT_URI: ""
  GOOGLE_REDIRECT_URI: ""
  HUGGINGFACE_API_BASE: ""
  LITELLM_PROXY_API_BASE: ""
  LITELLM_PROXY_API_URL: ""
  LM_STUDIO_API_BASE: ""
  NEXT_PUBLIC_HATCHET_DASHBOARD_URL: http://hatchet-dashboard:80
  NEXT_PUBLIC_R2R_DEPLOYMENT_URL: http://r2r:7272
  OLLAMA_API_BASE: ""
  OPENAI_API_BASE: ""
  PGADMIN_ENABLE_TLS: "false"
  PYTHONUNBUFFERED: "1"
  R2R_CONFIG_NAME: ""
  R2R_DASHBOARD_PORT: "3000"
  R2R_HATCHET_DASHBOARD_PORT: "80"
  R2R_HOST: 0.0.0.0
  R2R_LOG_LEVEL: INFO
  R2R_NGINX_PORT: "80"
  R2R_PORT: "7272"
  R2R_POSTGRES_DBNAME: r2r
  R2R_POSTGRES_HOST: postgresql
  R2R_POSTGRES_MAX_CONNECTIONS: "512"
  R2R_POSTGRES_PORT: "5432"
  R2R_POSTGRES_PROJECT_NAME: r2r_default
  R2R_POSTGRES_STATEMENT_CACHE_SIZE: "100"
  R2R_PROJECT_NAME: r2r_default
  R2R_SENTRY_DSN: ""
  R2R_SENTRY_ENVIRONMENT: ""
  R2R_SENTRY_PROFILES_SAMPLE_RATE: ""
  R2R_SENTRY_TRACES_SAMPLE_RATE: ""
  TELEMETRY_ENABLED: "false"
  VERTEX_LOCATION: ""
  VERTEX_PROJECT: ""
  HATCHET_ADMIN_ADDR: hatchet-api:7070
  HATCHET_CLIENT_HOST_PORT: hatchet-grpc:7070
  R2R_CONFIG_PATH: "/app/r2r.toml"
