---
apiVersion: v1
data:
  ANTHROPIC_API_KEY: ++++++++
  ANYSCALE_API_KEY: ++++++++
  AWS_ACCESS_KEY_ID: ++++++++
  AWS_SECRET_ACCESS_KEY: ++++++++
  AZURE_API_KEY: ++++++++
  AZURE_FOUNDRY_API_KEY: ++++++++
  COHERE_API_KEY: ++++++++
  GEMINI_API_KEY: ++++++++
  GITHUB_CLIENT_ID: ++++++++
  GITHUB_CLIENT_SECRET: ++++++++
  GOOGLE_APPLICATION_CREDENTIALS: ++++++++
  GOOGLE_CLIENT_ID: ++++++++
  GOOGLE_CLIENT_SECRET: ++++++++
  GROQ_API_KEY: ++++++++
  HUGGINGFACE_API_KEY: ++++++++
  LITELLM_PROXY_API_KEY: ++++++++
  LM_STUDIO_API_KEY: ++++++++
  OPENAI_API_KEY: ++++++++
  R2R_POSTGRES_PASSWORD: ++++++++
  R2R_POSTGRES_USER: ++++++++
  R2R_SECRET_KEY: ++++++++
  SENDGRID_API_KEY: ++++++++
  SERPER_API_KEY: ++++++++
  UNSTRUCTURED_API_KEY: ++++++++
kind: Secret
metadata:
  name: r2r-secrets
  namespace: ai-system
type: Opaque
---
apiVersion: v1
data:
  r2r.toml: ++++++++
kind: Secret
metadata:
  name: r2r-files
  namespace: ai-system
type: Opaque